import React from 'react'
import { Search, Bell, Edit2, Share2, Send, Sparkles } from 'lucide-react'
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
import Sidebar from '../components/Sidebar'
import Button from '../components/Button'
import Card from '../components/Card'
import './DashboardDetail.css'

const DashboardDetail: React.FC = () => {

  const kpiData = [
    { label: 'Total Revenue', value: '$1.2M', change: '+12%', changeType: 'positive', icon: '💰', context: 'vs. previous period' },
    { label: 'Active Users', value: '4,302', change: '+5.2%', changeType: 'positive', icon: '👥', context: 'vs. previous period' },
    { label: 'Avg. Deal Size', value: '$8.4k', change: '-2.1%', changeType: 'negative', icon: '🛍️', context: 'vs. previous period' },
    { label: 'Churn Rate', value: '2.1%', change: '-0.5%', changeType: 'positive', icon: '📉', context: 'Improvement from last Q' },
  ]

  const revenueData = [
    { month: 'Jan', revenue: 85000 },
    { month: 'Feb', revenue: 92000 },
    { month: 'Mar', revenue: 78000 },
    { month: 'Apr', revenue: 105000 },
    { month: 'May', revenue: 118000 },
    { month: 'Jun', revenue: 125000 },
    { month: 'Jul', revenue: 132000 },
  ]

  const trafficData = [
    { name: 'Direct', value: 45, color: '#3b82f6' },
    { name: 'Organic Search', value: 25, color: '#8b5cf6' },
    { name: 'Social', value: 30, color: '#7c3aed' },
  ]

  const transactions = [
    { customer: 'Acme Corp', date: 'Oct 2023', amount: '$12,450', status: 'Paid' },
    { customer: 'Tech Solutions', date: 'Oct 2023', amount: '$8,920', status: 'Paid' },
    { customer: 'Global Inc', date: 'Sep 2023', amount: '$15,680', status: 'Pending' },
  ]

  return (
    <div className="dashboard-detail-page">
      <Sidebar 
        title="Acme BI"
        subtitle="Enterprise Plan"
        projects={[
          { name: 'Marketing Q3', color: '#3b82f6' },
          { name: 'Sales Forecast', color: '#10b981' },
          { name: 'Product Usage', color: '#f59e0b' },
        ]}
      />

      <div className="main-content">
        <div className="top-header">
          <div className="breadcrumbs">
            <span>Dashboards</span>
            <span>/</span>
            <span>Sales Project</span>
            <span>/</span>
            <span>Q3 Sales Performance</span>
          </div>
          
          <div className="header-actions">
            <div className="search-bar">
              <Search size={18} />
              <input type="text" placeholder="Search..." />
            </div>
            <button className="icon-button">
              <Bell size={20} />
            </button>
            <div className="user-avatar-small">
              <span>JD</span>
            </div>
          </div>
        </div>

        <div className="dashboard-header">
          <div>
            <div className="dashboard-title-row">
              <h1 className="dashboard-title-main">Q3 Sales Performance</h1>
              <span className="preview-badge">Preview Mode</span>
            </div>
            <p className="dashboard-meta">Generated by AI • Last updated 2 mins ago</p>
          </div>
          
          <div className="dashboard-actions">
            <Button variant="outline" icon={<Edit2 size={16} />}>
              Edit Layout
            </Button>
            <Button variant="outline" icon={<Share2 size={16} />}>
              Share
            </Button>
            <Button variant="primary" icon={<Send size={16} />}>
              Publish
            </Button>
          </div>
        </div>

        <div className="filters-section">
          <span className="filters-label">FILTERS:</span>
          <select className="filter-dropdown">
            <option>Last 90 Days</option>
          </select>
          <select className="filter-dropdown">
            <option>Region: All Regions</option>
          </select>
          <select className="filter-dropdown">
            <option>Product: Enterprise</option>
          </select>
          <Button variant="ghost" size="sm">
            Reset All
          </Button>
        </div>

        <div className="kpi-grid">
          {kpiData.map((kpi, index) => (
            <Card key={index} className="kpi-card">
              <div className="kpi-header">
                <div className="kpi-icon">{kpi.icon}</div>
                <div className="kpi-label">{kpi.label}</div>
              </div>
              <div className="kpi-value">{kpi.value}</div>
              <div className={`kpi-change kpi-change-${kpi.changeType}`}>
                {kpi.change}
              </div>
              <div className="kpi-context">{kpi.context}</div>
            </Card>
          ))}
        </div>

        <div className="charts-grid">
          <Card className="chart-card">
            <div className="chart-header">
              <div>
                <h3 className="chart-title">Revenue Overview</h3>
                <p className="chart-subtitle">Monthly recurring revenue over time</p>
              </div>
            </div>
            <div className="chart-container">
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={revenueData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" />
                  <XAxis dataKey="month" stroke="var(--text-secondary)" />
                  <YAxis stroke="var(--text-secondary)" />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'var(--bg-card)', 
                      border: '1px solid var(--border-color)',
                      borderRadius: '8px',
                      color: 'var(--text-primary)'
                    }}
                  />
                  <Bar dataKey="revenue" fill="var(--blue-500)" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </Card>

          <Card className="chart-card">
            <div className="chart-header">
              <h3 className="chart-title">Traffic Source</h3>
            </div>
            <div className="pie-chart-container">
              <ResponsiveContainer width="100%" height={250}>
                <PieChart>
                  <Pie
                    data={trafficData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={100}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {trafficData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
              <div className="pie-center-text">
                <div className="pie-center-value">45%</div>
                <div className="pie-center-label">DIRECT</div>
              </div>
            </div>
            <div className="pie-legend">
              {trafficData.map((item, index) => (
                <div key={index} className="legend-item">
                  <div className="legend-color" style={{ backgroundColor: item.color }}></div>
                  <span>{item.name}: {item.value}%</span>
                </div>
              ))}
            </div>
          </Card>

          <Card className="chart-card">
            <div className="chart-header">
              <div>
                <h3 className="chart-title">Recent Transactions</h3>
              </div>
              <a href="#" className="view-all-link">View All</a>
            </div>
            <table className="transactions-table">
              <thead>
                <tr>
                  <th>CUSTOMER</th>
                  <th>DATE</th>
                  <th>AMOUNT</th>
                  <th>STATUS</th>
                </tr>
              </thead>
              <tbody>
                {transactions.map((tx, index) => (
                  <tr key={index}>
                    <td>{tx.customer}</td>
                    <td>{tx.date}</td>
                    <td>{tx.amount}</td>
                    <td><span className="status-badge-small">{tx.status}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>

          <Card className="chart-card">
            <div className="chart-header">
              <h3 className="chart-title">Geographic Distribution</h3>
            </div>
            <div className="geo-placeholder">
              <div className="placeholder-text">300x300</div>
            </div>
          </Card>
        </div>

        <div className="ai-overlay">
          <Sparkles size={20} />
          <span>Ask AI a question about this dashboard...</span>
          <span style={{ fontSize: '18px' }}>↑</span>
        </div>
      </div>
    </div>
  )
}

export default DashboardDetail
